# Introduction-Features-Array

In [1]:
liste = [1,2,3,4,5]

In [2]:
liste

[1, 2, 3, 4, 5]

In [2]:
import numpy as np

In [5]:
array = np.array(liste)

In [11]:
print("one-dimensional",array)

one-dimensional [1 2 3 4 5]


In [7]:
liste = [1,2,3,4,5]
liste2 = [6,7,8,9,10]

In [16]:
array2 = np.array([liste,liste2])
print("two-dimensional :",array2)
print("Shape :",array2.shape)
print("dimension :",array2.ndim)
print("size :",array2.size)
print("Type :",type(array2))
print("Data :",array2.dtype)

two-dimensional : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape : (2, 5)
dimension : 2
size : 10
Type : <class 'numpy.ndarray'>
Data : int64


In [21]:
array3 = array2.reshape((5,2)) # array2 Shape : (2, 5) chance shape reshape
print("array2 Shape :",array2.shape)
print("array3 Shape :",array3.shape)

array2 Shape : (2, 5)
array3 Shape : (5, 2)


In [24]:
# zeros matrix

zero = np.zeros((3,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zero[0,2] = 7 # update
zero

array([[0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
empty = np.empty((3,5))
empty

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
full = np.full((2,7),10)
full

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [32]:
arange = np.arange(0,10,2)
arange

array([0, 2, 4, 6, 8])

In [34]:
linspace = np.linspace(0,10,20) # 10 numbers between 0 and 20
linspace

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [36]:
eye = np.eye(10)
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Mathematical Operations

In [36]:
x = np.array([2,4,6,7,9])
y = np.array([12,14,16,17,19])
print(x+y)
print(y-x)
print(y*x)
print(x**2)
print(np.cos(y))
print(x<3)

[14 18 22 24 28]
[10 10 10 10 10]
[ 24  56  96 119 171]
[ 4 16 36 49 81]
[ 0.84385396  0.13673722 -0.95765948 -0.27516334  0.98870462]
[ True False False False False]


In [37]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[2,2,4,4],[5,5,6,6]])
a.dot(b.T)

array([[ 34,  57],
       [ 82, 145]])

In [38]:
array1 = np.random.random((5,5))
array1

array([[0.69021428, 0.10463005, 0.49654704, 0.31502075, 0.1067478 ],
       [0.23594605, 0.21867922, 0.21682396, 0.64818758, 0.85425025],
       [0.88534448, 0.19565966, 0.88097987, 0.3121213 , 0.28967468],
       [0.18426027, 0.8912151 , 0.31548735, 0.07737639, 0.51008466],
       [0.48419699, 0.56459529, 0.62310912, 0.16020884, 0.66978552]])

In [39]:
array1 = np.random.random((5,5))
array1.sum()

12.49321252217953

In [40]:
array1 = np.random.random((5,5))
array1.max()

0.9924549575688273

In [41]:
array1 = np.random.random((5,5))
array1.min()

0.011926783185204237

In [42]:
array2 = np.random.randint(0,10,(4,4))
array2

array([[5, 4, 0, 9],
       [0, 3, 8, 1],
       [0, 9, 3, 8],
       [6, 4, 5, 4]])

In [43]:
array2 = np.random.randint(0,10,(4,4))
print(array2)
print(" ")
print("column sum :",array2.sum(axis= 0))
print("row sum :",array2.sum(axis= 1))

[[0 4 7 7]
 [0 5 4 1]
 [6 4 9 9]
 [0 8 3 5]]
 
column sum : [ 6 21 23 22]
row sum : [18 10 28 16]


In [44]:
print("square root :",np.sqrt(array2))
print(" ")
print("product of squares :",np.square(array2))

square root : [[0.         2.         2.64575131 2.64575131]
 [0.         2.23606798 2.         1.        ]
 [2.44948974 2.         3.         3.        ]
 [0.         2.82842712 1.73205081 2.23606798]]
 
product of squares : [[ 0 16 49 49]
 [ 0 25 16  1]
 [36 16 81 81]
 [ 0 64  9 25]]


# Indexing and Shredding

In [48]:
array = np.array([1,2,3,4,5])

In [51]:
array[0]
array[1]
array[1:4]

array([2, 3, 4])

In [58]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(array2)
print(array2[2,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
15


In [59]:
print(array2[0:2,3:5]) # comma left row left column 

[[ 4  5]
 [ 9 10]]


In [60]:
print(array2[:,3:5])

[[ 4  5]
 [ 9 10]
 [14 15]]


# Sizing and Merging

In [70]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(array)
x = array.ravel() 
print("rectification :",x)
print("dimesion :",x.ndim)
y = array.reshape(15,)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
rectification : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
dimesion : 1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [72]:
array2 = y.reshape(5,3)
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [75]:
x.resize(5,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [78]:
array3 = np.array([[1,2],[3,4]])
array4 = np.array([[5,6],[7,8]])
array5 =np.vstack((array3,array4))
array6 =np.hstack((array3,array4))
print(array5)
print(array6)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
